version: "3.7"
services:
  postgraphile:
    build: .
    ports:
      - 5000:5000
    command: --cors --schema forum_example --append-plugins postgraphile-plugin-connection-filter,@graphile-contrib/pg-simplify-inflector --enhance-graphiql --jwt-token-identifier forum_example_private.jwt_token --retry-on-init-fail --jwt-secret secret --default-role forum_example_anonymous --extended-errors severity,code,detail,hint,position,internalPosition,internalQuery,where,schema,table,column,dataType,constraint,file,line,routine
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/poc-forum
      DEBUG: postgraphile:graphql,postgraphile:request,postgraphile:postgres*

  graphile-worker:
    build: graphile-worker
    volumes:
      - ./graphile-worker/tasks/:/tasks/
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/poc-forum

  graphql-voyager:
    image: harobed/graphql-voyager:latest
    ports:
      - 3001:3001
    environment:
      GRAPHQL_ENDPOINT: http://127.0.0.1:5000/graphql

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: poc-forum
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/:/var/lib/postgresql/

networks:
   default:
     name: poc-postgraphile-forum